### ISSUE TITLE
Paradise EGA hangs after memory test on NuXT v2.0

### ISSUE THREAD

**Issue by trguhq** [skiselev/8088_bios#77]
I am trying a Paradise EGA (PEGA2 I believe) and it is hanging after the memory test. Onboard SVGA works as does an IBM PGC (VGA/EGA BIOS). Is this related to NuXT or the BIOS?

Confirmation of the issue at https://www.vogons.org/viewtopic.php?t=96507 where the OP says "it hangs right after starting searching for option ROMs (code 40)."

**Comment by skiselev** [comment]
What 8088 BIOS version do you run?
If it is not the latest 1.0.0, I'd recommend upgrading the BIOS and trying again, as some bugs were fixed in the newer versions.

By the way, POST code 0x30 happens way after EGA/VGA BIOS extension initialization, which uses POST codes 0x10 and 0x11.

**Comment by trguhq** [comment]
I updated to the 1.0.0 available on the NuXT v2 github (100_NV20.BIN). It still hangs after the memory test.

**Comment by trguhq** [comment]
I actually have an NuXT v1.2. I guess I flashed the wrong bios.
